version: 2.1

jobs:
  build:
    docker: none # Disable Docker to run directly on Ubuntu
    machine:
      image: ubuntu-latest

    working_directory: ~/repo

    steps:
      - checkout

      # Install OpenJDK 17
      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt update
            sudo apt install -y openjdk-17-jdk

      # Set Java 17 environment variables
      - run:
          name: Set Java 17 Environment
          command: |
            echo "export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $BASH_ENV
            echo "export PATH=$JAVA_HOME/bin:$PATH" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Build and Test
          command: ./gradlew build --scan

workflows:
  version: 2
  build_only_main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
