version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build and Test
          command: ./gradlew build --scan

workflows:
  version: 2
  build_only_main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
